package ux;


import java.awt.BorderLayout;
import java.io.IOException;

import javax.swing.JPanel;

/**
 *
 * @author migue
 */
public class PanelSelection extends JPanel {

    Principal principal = null;
    PanelHorse panelHorse1 = null;
    PanelHorse panelHorse2 = null;
    PanelHorse panelHorse3 = null;
    PanelHorse panelHorse4 = null;
    PanelHorse panelHorse5 = null;
    PanelHorse panelHorse6 = null;

    /** Creates new form PanelSeleccion
     * @param p 
     * @throws IOException */
    public PanelSelection(Principal p) throws IOException {
        principal = p;
        
        initComponents();
        
        //Panel Horse1
        panelHorse1 = new PanelHorse(this);
        panelHorse1.setSize(120,150);
        panelHorse1.setLocation(0,0);
        
        jpHorse1.removeAll();
        jpHorse1.add(panelHorse1, BorderLayout.CENTER);
        panelHorse1.setVisible(true);
        jpHorse1.revalidate();
        jpHorse1.repaint();
        
        //Panel Horse2
        panelHorse2 = new PanelHorse(this);
        panelHorse2.setSize(120,150);
        panelHorse2.setLocation(0,0);
        
        jpHorse2.removeAll();
        jpHorse2.add(panelHorse2, BorderLayout.CENTER);
        panelHorse2.setVisible(true);
        jpHorse2.revalidate();
        jpHorse2.repaint();
        
        //Panel Horse3
        panelHorse3 = new PanelHorse(this);
        panelHorse3.setSize(120,150);
        panelHorse3.setLocation(0,0);
        
        jpHorse3.removeAll();
        jpHorse3.add(panelHorse3, BorderLayout.CENTER);
        panelHorse3.setVisible(true);
        jpHorse3.revalidate();
        jpHorse3.repaint();
        
        
        //Panel Horse4
        panelHorse4 = new PanelHorse(this);
        panelHorse4.setSize(120,150);
        panelHorse4.setLocation(0,0);
        
        jpHorse4.removeAll();
        jpHorse4.add(panelHorse4, BorderLayout.CENTER);
        panelHorse4.setVisible(true);
        jpHorse4.revalidate();
        jpHorse4.repaint();
        
        //Panel Horse5
        panelHorse5 = new PanelHorse(this);
        panelHorse5.setSize(120,150);
        panelHorse5.setLocation(0,0);
        
        jpHorse5.removeAll();
        jpHorse5.add(panelHorse5, BorderLayout.CENTER);
        panelHorse5.setVisible(true);
        jpHorse5.revalidate();
        jpHorse5.repaint();
        
         //Panel Horse6
        panelHorse6 = new PanelHorse(this);
        panelHorse6.setSize(120,150);
        panelHorse6.setLocation(0,0);
        
        jpHorse6.removeAll();
        jpHorse6.add(panelHorse6, BorderLayout.CENTER);
        panelHorse6.setVisible(true);
        jpHorse6.revalidate();
        jpHorse6.repaint();
        
        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jpHorse1 = new javax.swing.JPanel();
        jpHorse2 = new javax.swing.JPanel();
        jpHorse3 = new javax.swing.JPanel();
        jpHorse4 = new javax.swing.JPanel();
        jpHorse5 = new javax.swing.JPanel();
        jpHorse6 = new javax.swing.JPanel();

        jpHorse1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHorse1Layout = new javax.swing.GroupLayout(jpHorse1);
        jpHorse1.setLayout(jpHorse1Layout);
        jpHorse1Layout.setHorizontalGroup(
            jpHorse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpHorse1Layout.setVerticalGroup(
            jpHorse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jpHorse2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHorse2Layout = new javax.swing.GroupLayout(jpHorse2);
        jpHorse2.setLayout(jpHorse2Layout);
        jpHorse2Layout.setHorizontalGroup(
            jpHorse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpHorse2Layout.setVerticalGroup(
            jpHorse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jpHorse3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHorse3Layout = new javax.swing.GroupLayout(jpHorse3);
        jpHorse3.setLayout(jpHorse3Layout);
        jpHorse3Layout.setHorizontalGroup(
            jpHorse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpHorse3Layout.setVerticalGroup(
            jpHorse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jpHorse4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHorse4Layout = new javax.swing.GroupLayout(jpHorse4);
        jpHorse4.setLayout(jpHorse4Layout);
        jpHorse4Layout.setHorizontalGroup(
            jpHorse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpHorse4Layout.setVerticalGroup(
            jpHorse4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jpHorse5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHorse5Layout = new javax.swing.GroupLayout(jpHorse5);
        jpHorse5.setLayout(jpHorse5Layout);
        jpHorse5Layout.setHorizontalGroup(
            jpHorse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpHorse5Layout.setVerticalGroup(
            jpHorse5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jpHorse6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpHorse6Layout = new javax.swing.GroupLayout(jpHorse6);
        jpHorse6.setLayout(jpHorse6Layout);
        jpHorse6Layout.setHorizontalGroup(
            jpHorse6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpHorse6Layout.setVerticalGroup(
            jpHorse6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpHorse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpHorse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpHorse3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpHorse4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpHorse5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpHorse6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHorse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpHorse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHorse3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpHorse4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpHorse5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpHorse6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JPanel jpHorse1;
    private javax.swing.JPanel jpHorse2;
    private javax.swing.JPanel jpHorse3;
    private javax.swing.JPanel jpHorse4;
    private javax.swing.JPanel jpHorse5;
    private javax.swing.JPanel jpHorse6;
    // End of variables declaration                   

    public void initiateHorses(int horseNumber, String horseName, String imagePath) throws IOException {
        
        switch (horseNumber){
            case 1: panelHorse1.initiateHorse(horseName, imagePath);
            case 2: panelHorse2.initiateHorse(horseName, imagePath);
            case 3: panelHorse3.initiateHorse(horseName, imagePath);
            case 4: panelHorse4.initiateHorse(horseName, imagePath);
            case 5: panelHorse5.initiateHorse(horseName, imagePath);
            case 6: panelHorse6.initiateHorse(horseName, imagePath);
        }
        
    }



	public void loadHorseInfo(String text) {
		
		principal.loadHorseInfo(text);
	}

}


