package ux;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.SystemColor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class PanelHorseInfo extends JPanel {
	private JTextField txtApuesta;
	private Principal principal;
	
	private JLabel lblPhoto;
    
	private JLabel lblNombre;
    
	private JLabel lblNmero;
    
	private  JLabel lblName;
    
	private JLabel lblCarrerasGanadas;
    
	private JLabel lblNumber;
    
	private  JLabel lblWonraces;
	private JTextField txtCedulaBettor;
    
	
	/**
	 * Create the panel.
	 */
	 public PanelHorseInfo(Principal p) {
		setBackground(Color.WHITE);
		principal = p;
		   
	       initComponents();
	   }

	   /**
	    * This method is called from within the constructor to initialize the form.
	    * WARNING: Do NOT modify this code. The content of this method is always
	    * regenerated by the Form Editor.
	    */
	   @SuppressWarnings("unchecked")
	   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	   private void initComponents() {
	       
		   lblPhoto = new JLabel("");
	       
	       lblNombre = new JLabel("Nombre:");
	       lblNombre.setFont(new Font("Tahoma", Font.PLAIN, 15));
	       
	       lblNmero = new JLabel("N\u00FAmero:");
	       lblNmero.setFont(new Font("Tahoma", Font.PLAIN, 15));
	       
	       lblName = new JLabel("");
	       lblName.setFont(new Font("Tahoma", Font.BOLD, 15));
	       
	       lblCarrerasGanadas = new JLabel("Carreras ganadas:");
	       lblCarrerasGanadas.setFont(new Font("Tahoma", Font.PLAIN, 15));
	       
	       lblNumber = new JLabel("");
	       lblNumber.setFont(new Font("Tahoma", Font.BOLD, 15));
	       
	       lblWonraces = new JLabel("");
	       lblWonraces.setFont(new Font("Tahoma", Font.BOLD, 15));
	       
	       
	       
	       JPanel panel = new JPanel();
	       panel.setBackground(new Color(220, 220, 220));

	       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	       layout.setHorizontalGroup(
	       	layout.createParallelGroup(Alignment.LEADING)
	       		.addGroup(layout.createSequentialGroup()
	       			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	       				.addGroup(layout.createSequentialGroup()
	       					.addGap(24)
	       					.addComponent(lblPhoto, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
	       					.addGap(18)
	       					.addGroup(layout.createParallelGroup(Alignment.LEADING)
	       						.addGroup(layout.createSequentialGroup()
	       							.addComponent(lblNombre)
	       							.addPreferredGap(ComponentPlacement.UNRELATED)
	       							.addComponent(lblName))
	       						.addGroup(layout.createSequentialGroup()
	       							.addComponent(lblNmero)
	       							.addPreferredGap(ComponentPlacement.UNRELATED)
	       							.addComponent(lblNumber))
	       						.addGroup(layout.createSequentialGroup()
	       							.addComponent(lblCarrerasGanadas)
	       							.addGap(10)
	       							.addComponent(lblWonraces))))
	       				.addGroup(layout.createSequentialGroup()
	       					.addContainerGap()
	       					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 398, GroupLayout.PREFERRED_SIZE)))
	       			.addContainerGap(42, Short.MAX_VALUE))
	       );
	       layout.setVerticalGroup(
	       	layout.createParallelGroup(Alignment.LEADING)
	       		.addGroup(layout.createSequentialGroup()
	       			.addContainerGap()
	       			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	       				.addGroup(layout.createSequentialGroup()
	       					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	       						.addComponent(lblNombre)
	       						.addComponent(lblName))
	       					.addPreferredGap(ComponentPlacement.UNRELATED)
	       					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	       						.addComponent(lblNmero)
	       						.addComponent(lblNumber))
	       					.addPreferredGap(ComponentPlacement.UNRELATED)
	       					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	       						.addComponent(lblCarrerasGanadas)
	       						.addComponent(lblWonraces)))
	       				.addComponent(lblPhoto, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
	       			.addPreferredGap(ComponentPlacement.RELATED)
	       			.addComponent(panel, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
	       			.addContainerGap())
	       );
	       
	       JLabel lblapustaPorEste = new JLabel("\u00A1Apu\u00E9sta por este caballo!");
	       lblapustaPorEste.setFont(new Font("Tahoma", Font.BOLD, 12));
	       
	       txtApuesta = new JTextField();
	       txtApuesta.setColumns(10);
	       
	      
	       JButton btnApostar = new JButton("APOSTAR");
	      
	       btnApostar.addMouseListener(new MouseAdapter() {
	       	@Override
	       	public void mouseClicked(MouseEvent arg0) {
	       		principal.bet(txtCedulaBettor.getText(), Double.parseDouble(txtApuesta.getText()), Integer.parseInt(lblNumber.getText()));
	       		
	       	}
	       });
	       btnApostar.setBackground(SystemColor.textHighlight);
	       btnApostar.setFont(new Font("Tahoma", Font.BOLD, 15));
	       btnApostar.setForeground(SystemColor.desktop);
	       
	       JLabel lblValorApuesta = new JLabel("Valor Apuesta:");
	       
	       txtCedulaBettor = new JTextField();
	       txtCedulaBettor.setColumns(10);
	       
	       JLabel lblCdula = new JLabel("C\u00E9dula del apostador");
	       GroupLayout gl_panel = new GroupLayout(panel);
	       gl_panel.setHorizontalGroup(
	       	gl_panel.createParallelGroup(Alignment.LEADING)
	       		.addGroup(gl_panel.createSequentialGroup()
	       			.addContainerGap(39, Short.MAX_VALUE)
	       			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
	       				.addGroup(Alignment.TRAILING, gl_panel.createSequentialGroup()
	       					.addComponent(lblCdula)
	       					.addGap(24))
	       				.addGroup(Alignment.TRAILING, gl_panel.createSequentialGroup()
	       					.addComponent(txtCedulaBettor, GroupLayout.PREFERRED_SIZE, 143, GroupLayout.PREFERRED_SIZE)
	       					.addPreferredGap(ComponentPlacement.RELATED)))
	       			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
	       				.addGroup(gl_panel.createSequentialGroup()
	       					.addGap(36)
	       					.addComponent(txtApuesta, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
	       					.addContainerGap(31, Short.MAX_VALUE))
	       				.addGroup(Alignment.TRAILING, gl_panel.createSequentialGroup()
	       					.addPreferredGap(ComponentPlacement.RELATED)
	       					.addComponent(lblValorApuesta)
	       					.addGap(71))))
	       		.addGroup(Alignment.TRAILING, gl_panel.createSequentialGroup()
	       			.addContainerGap(151, Short.MAX_VALUE)
	       			.addComponent(btnApostar)
	       			.addGap(142))
	       		.addGroup(Alignment.TRAILING, gl_panel.createSequentialGroup()
	       			.addContainerGap(121, Short.MAX_VALUE)
	       			.addComponent(lblapustaPorEste)
	       			.addGap(115))
	       );
	       gl_panel.setVerticalGroup(
	       	gl_panel.createParallelGroup(Alignment.LEADING)
	       		.addGroup(Alignment.TRAILING, gl_panel.createSequentialGroup()
	       			.addContainerGap()
	       			.addComponent(lblapustaPorEste)
	       			.addGap(18)
	       			.addGroup(gl_panel.createParallelGroup(Alignment.TRAILING)
	       				.addGroup(gl_panel.createSequentialGroup()
	       					.addGap(20)
	       					.addComponent(txtApuesta, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
	       				.addGroup(Alignment.LEADING, gl_panel.createSequentialGroup()
	       					.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
	       						.addComponent(lblCdula)
	       						.addComponent(lblValorApuesta))
	       					.addPreferredGap(ComponentPlacement.UNRELATED)
	       					.addComponent(txtCedulaBettor, GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
	       			.addPreferredGap(ComponentPlacement.UNRELATED)
	       			.addComponent(btnApostar)
	       			.addContainerGap())
	       );
	       panel.setLayout(gl_panel);
	       this.setLayout(layout);
	   }// </editor-fold>                        

	public void loadHorseInfo(String text, int number, int raceswon, String path) {
		lblWonraces.setText(raceswon+"");
		lblNumber.setText(number+"");
		lblName.setText(text);
		lblPhoto.setIcon(new ImageIcon(path));
		
	}
}
